### ISSUE TITLE
bug 报告|疑问

### ISSUE THREAD

**Issue by 578223592** [Xiaoccer/ARC_Cache#1]
`move_to_lru`函数实现中移动了entry后为何没有对ArcEntryPtr entry的iterator进行修改

https://github.com/Xiaoccer/ARC_Cache/blob/52cd55d4a7c55dd8bd2606cfd2923d050734ccc6/arc.h#L52

**Comment by Xiaoccer** [comment]
可以看看 std::list 中 splice 的实现
